spring:
  profiles:
    active: dev-ms
  security:
    filter:
      order: 5
  http:
    encoding:
      force: true

logging:
  level:
    org:
      springframework.web: INFO
      hibernate: INFO
    pl:
      simplecoding: INFO
  file: ${MS_PRED_LOG_PATH:.}prediction-app.log